// Zod schemas for Proxenio MCP tool inputs
// MCP SDK expects raw Zod shapes (plain objects of Zod types), not ZodObjects

import { z } from "zod";

export const SetApiKeyShape = {
  api_key: z
    .string()
    .min(36, "API key must be 36 characters")
    .max(36, "API key must be 36 characters")
    .startsWith("prx_", "API key must start with 'prx_'")
    .describe(
      "Proxenio API key (36 chars, starts with 'prx_'). " +
      "Generated by the human principal at https://www.proxenio.ai/agents"
    ),
};

export const GetMatchesShape = {
  filter_type: z
    .enum(["all", "premium", "strong", "regular"])
    .default("all")
    .describe("Filter matches by type: 'all', 'premium', 'strong', or 'regular'"),
  filter_status: z
    .enum(["all", "pending", "accepted"])
    .default("all")
    .describe("Filter matches by status: 'all', 'pending', or 'accepted'"),
  min_score: z
    .number()
    .int()
    .min(40)
    .max(100)
    .default(40)
    .describe("Minimum match score to include (40-100). Default: 40"),
};

export const AcceptMatchShape = {
  match_id: z
    .string()
    .uuid("match_id must be a valid UUID")
    .describe(
      "UUID of the match to accept. Get this from proxenio_get_matches. " +
      "The principal must be the receiving party (user_b), not the requester."
    ),
};

export interface SetApiKeyInput {
  api_key: string;
}

export interface GetMatchesInput {
  filter_type: "all" | "premium" | "strong" | "regular";
  filter_status: "all" | "pending" | "accepted";
  min_score: number;
}

export interface AcceptMatchInput {
  match_id: string;
}

export const GetDealsShape = {
  filter_status: z
    .enum(["all", "open", "closed"])
    .default("all")
    .describe("Filter deals by status: 'all', 'open', or 'closed'"),
};

export const RequestIntroShape = {
  match_id: z
    .string()
    .uuid("match_id must be a valid UUID")
    .describe(
      "UUID of the match to request an introduction for. Get this from proxenio_get_matches."
    ),
  context: z
    .string()
    .max(500, "Context must be 500 characters or fewer")
    .optional()
    .describe(
      "Optional message to the counterparty (max 500 characters)"
    ),
};

export const LogOutcomeShape = {
  deal_id: z
    .string()
    .uuid("deal_id must be a valid UUID")
    .describe(
      "UUID of the deal to log an outcome for. Get this from proxenio_get_deals."
    ),
  outcome_type: z
    .enum([
      "Intro",
      "Pipeline Progress",
      "Agreement or Deal",
      "Results or Impact",
      "Negative or Closing",
      "Neutral or Respectful Close",
    ])
    .describe(
      "Type of outcome: 'Intro', 'Pipeline Progress', 'Agreement or Deal', 'Results or Impact', 'Negative or Closing', or 'Neutral or Respectful Close'"
    ),
  outcome_description: z
    .string()
    .max(1000, "Outcome description must be 1000 characters or fewer")
    .optional()
    .describe(
      "Optional description of the outcome (max 1000 characters)"
    ),
};

export interface GetDealsInput {
  filter_status: "all" | "open" | "closed";
}

export interface RequestIntroInput {
  match_id: string;
  context?: string;
}

export interface LogOutcomeInput {
  deal_id: string;
  outcome_type: string;
  outcome_description?: string;
}
