// Zod schemas for Proxenio MCP tool inputs
// MCP SDK expects raw Zod shapes (plain objects of Zod types), not ZodObjects

import { z } from "zod";

export const SetApiKeyShape = {
  api_key: z
    .string()
    .min(36, "API key must be 36 characters")
    .max(36, "API key must be 36 characters")
    .startsWith("prx_", "API key must start with 'prx_'")
    .describe(
      "Proxenio API key (36 chars, starts with 'prx_'). " +
      "Generated by the human principal at https://www.proxenio.ai/agents"
    ),
};

export const GetMatchesShape = {
  filter_type: z
    .enum(["all", "premium", "strong", "regular"])
    .default("all")
    .describe("Filter matches by type: 'all', 'premium', 'strong', or 'regular'"),
  filter_status: z
    .enum(["all", "pending", "accepted"])
    .default("all")
    .describe("Filter matches by status: 'all', 'pending', or 'accepted'"),
  min_score: z
    .number()
    .int()
    .min(40)
    .max(100)
    .default(40)
    .describe("Minimum match score to include (40-100). Default: 40"),
};

export const AcceptMatchShape = {
  match_id: z
    .string()
    .uuid("match_id must be a valid UUID")
    .describe(
      "UUID of the match to accept. Get this from proxenio_get_matches. " +
      "The principal must be the receiving party (user_b), not the requester."
    ),
};

export interface SetApiKeyInput {
  api_key: string;
}

export interface GetMatchesInput {
  filter_type: "all" | "premium" | "strong" | "regular";
  filter_status: "all" | "pending" | "accepted";
  min_score: number;
}

export interface AcceptMatchInput {
  match_id: string;
}
