// Proxenio MCP Tool Registration
import type { ZodTypeAny } from "zod";
// Registers all tools with the MCP server

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  SetApiKeyShape,
  GetMatchesShape,
  AcceptMatchShape,
} from "../schemas/inputs.js";
import {
  setApiKey,
  hasApiKey,
  getMatches,
  acceptMatch,
} from "../services/api.js";
import {
  formatMatchesMarkdown,
  formatAcceptMarkdown,
} from "../services/formatting.js";
import { PROXENIO_URL, RATE_LIMIT_PER_HOUR } from "../constants.js";

/**
 * Register all Proxenio tools on the MCP server.
 */
export function registerTools(server: McpServer): void {
  // ─── Tool 1: Platform Discovery ───
  server.registerTool(
    "proxenio_discover",
    {
      title: "Discover Proxenio Platform",
      description: `Get information about the Proxenio platform and its agent API.

Proxenio is a verified intent network for professional deal-making. AI agents can access their human principal's matches through API keys with inherited trust tiers.

This tool requires no authentication. Use it to understand the platform before connecting.

Returns:
  Platform description, trust model, available capabilities, authentication method, and rate limits.

Examples:
  - Use when: "What is Proxenio?" or "How do I connect to Proxenio?"
  - Use when: Agent needs to understand what Proxenio offers before authenticating
  - Don't use when: You already know about Proxenio and just need to read matches`,
      inputSchema: {},
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async () => {
      const info = [
        "# Proxenio — Verified Intent Network",
        "",
        "## What It Is",
        "Proxenio matches verified professionals based on declared intent and confirmed outcomes.",
        "Trust is earned through behavioral proof, not claimed through profiles.",
        "",
        "## Agent Access",
        `- **Base URL**: ${PROXENIO_URL}/api/agent`,
        "- **Auth**: API key via `X-Proxenio-Key` header (prefix: `prx_`, 36 chars)",
        "- **Key provisioning**: Human principal generates keys at /agents after email verification",
        "- **Max keys**: 3 per user",
        `- **Rate limit**: ${RATE_LIMIT_PER_HOUR} requests/hour per key`,
        "",
        "## Trust Model",
        "- Agents inherit their human principal's trust tier at request time",
        "- Trust tiers: 0 (Unverified) → 1 (Starter) → 2 (Active) → 3 (Trusted) → 4 (Proven)",
        "- Agents cannot build independent trust or exceed their principal's tier",
        "- Counterparties always see a transparency badge when interacting with an agent's principal",
        "",
        "## Available Tools",
        "1. `proxenio_set_api_key` — Configure your API key (required before other operations)",
        "2. `proxenio_get_matches` — Read principal's verified professional matches",
        "3. `proxenio_accept_match` — Accept an introduction request on behalf of principal",
        "",
        "## Scope Limitations",
        "- Agents CAN read matches and accept introductions",
        "- Agents CANNOT request intros, close deals, log outcomes, or modify settings",
        "- Agents CANNOT bypass the matching engine's skip layers or tier gates",
        "",
        `**Status**: ${hasApiKey() ? "✓ API key configured" : "⚠ No API key set — use proxenio_set_api_key first"}`,
        "",
        `**Links**: [Platform](${PROXENIO_URL}) · [API Docs](${PROXENIO_URL}/agents/docs) · [OpenAPI Spec](${PROXENIO_URL}/api/agent/openapi.json)`,
      ];

      return {
        content: [{ type: "text" as const, text: info.join("\n") }],
      };
    }
  );

  // ─── Tool 2: Set API Key ───
  (server.registerTool as any)(
    "proxenio_set_api_key",
    {
      title: "Set Proxenio API Key",
      description: `Configure the API key for authenticating with Proxenio's agent API.

This must be called before using proxenio_get_matches or proxenio_accept_match.

The API key is generated by a verified human principal at ${PROXENIO_URL}/agents. Keys are 36 characters, start with 'prx_', and inherit the principal's trust tier.

Args:
  - api_key (string): The full API key starting with 'prx_' (36 characters)

Returns:
  Confirmation that the key was set, or an error if the format is invalid.

Examples:
  - Use when: Setting up Proxenio access for the first time
  - Use when: Switching to a different principal's API key
  - Don't use when: Key is already configured and working`,
      inputSchema: SetApiKeyShape as unknown as ZodTypeAny,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async (params: { api_key: string }) => {
      try {
        setApiKey(params.api_key);
        const prefix = params.api_key.substring(0, 12);
        return {
          content: [
            {
              type: "text" as const,
              text: `✓ API key configured (${prefix}…). You can now use proxenio_get_matches and proxenio_accept_match.`,
            },
          ],
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 3: Get Matches ───
  (server.registerTool as any)(
    "proxenio_get_matches",
    {
      title: "Get Proxenio Matches",
      description: `Read the principal's verified professional matches from Proxenio.

Returns matches sorted by match score (descending). Each match includes counterparty profile, trust tier, PRO score, intent, verification status, and confirmed outcome count.

Requires: API key must be set via proxenio_set_api_key first.

The agent sees exactly what the human principal sees — same skip engine layers, same tier gates, same minimum score (40). Matches below 40 are never returned.

Args:
  - filter_type ('all' | 'premium' | 'strong' | 'regular'): Filter by match quality tier (default: 'all')
  - filter_status ('all' | 'pending' | 'accepted'): Filter by match status (default: 'all')
  - min_score (number, 40-100): Minimum match score threshold (default: 40)

Returns:
  Principal info, list of matches with full counterparty profiles, trust signals, and rate limit status.

Examples:
  - Use when: "Show me my matches" or "What professional connections are available?"
  - Use when: "Find my best matches" -> use filter_type='premium'
  - Use when: "Which introductions are pending?" -> use filter_status='pending'
  - Don't use when: API key has not been set yet (use proxenio_set_api_key first)

Error Handling:
  - Returns auth error if API key is invalid or revoked
  - Returns rate limit error if ${RATE_LIMIT_PER_HOUR} requests/hour exceeded
  - Returns empty list if principal has no matches (profile may be incomplete)`,
      inputSchema: GetMatchesShape as unknown as ZodTypeAny,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async (params: { filter_type: string; filter_status: string; min_score: number }) => {
      try {
        const { data, rateLimit } = await getMatches();

        // Apply client-side filters
        let filtered = data.matches;

        if (params.filter_type !== "all") {
          filtered = filtered.filter((m) => m.match_type === params.filter_type);
        }
        if (params.filter_status !== "all") {
          filtered = filtered.filter((m) => m.status === params.filter_status);
        }
        if (params.min_score > 40) {
          filtered = filtered.filter((m) => m.match_score >= params.min_score);
        }

        const filteredResponse = { ...data, matches: filtered, meta: { ...data.meta, total_matches: filtered.length } };
        const markdown = formatMatchesMarkdown(filteredResponse, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 4: Accept Match ───
  (server.registerTool as any)(
    "proxenio_accept_match",
    {
      title: "Accept Proxenio Introduction",
      description: `Accept an introduction request on behalf of the human principal.

This creates a deal between the principal and the counterparty. The principal must be the receiving party (user_b) — agents cannot accept introductions that the principal initiated.

IMPORTANT: This is an action with real consequences. It connects two professionals and creates a deal container. Only accept matches that align with the principal's stated intent.

Requires: API key must be set via proxenio_set_api_key first.

Args:
  - match_id (string, UUID): The match ID to accept. Get this from proxenio_get_matches results.

Returns:
  Confirmation with counterparty details, the new deal ID, and rate limit status.

Guard rails enforced by the API:
  - Principal must be a participant in the match
  - Principal must be the receiving party (user_b), not the requester
  - Match must have an active status
  - An introduction request must exist and be in pending/awaiting_consent state
  - Agent cannot accept the principal's own outgoing requests

Examples:
  - Use when: Principal wants to accept a specific pending introduction
  - Use when: Agent decides a match aligns with principal's intent and should be accepted
  - Don't use when: You haven't checked the match details first (use proxenio_get_matches)
  - Don't use when: The match was initiated by the principal (agent can only accept incoming)

Error Handling:
  - 400: Match not in correct state, no intro request exists
  - 403: Principal is not authorized (e.g., they are the requester, not receiver)
  - 404: Match ID not found
  - 429: Rate limit exceeded`,
      inputSchema: AcceptMatchShape as unknown as ZodTypeAny,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async (params: { match_id: string }) => {
      try {
        const { data, rateLimit } = await acceptMatch(params.match_id);
        const markdown = formatAcceptMarkdown(data, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );
}
