// Proxenio MCP Tool Registration
// Registers all tools with the MCP server

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  SetApiKeyShape,
  GetMatchesShape,
  AcceptMatchShape,
  GetDealsShape,
  RequestIntroShape,
  LogOutcomeShape,
} from "../schemas/inputs.js";
import {
  setApiKey,
  hasApiKey,
  getMatches,
  acceptMatch,
  getDeals,
  requestIntro,
  logOutcome,
} from "../services/api.js";
import {
  formatMatchesMarkdown,
  formatAcceptMarkdown,
  formatDealsMarkdown,
  formatIntroRequestMarkdown,
  formatOutcomeMarkdown,
} from "../services/formatting.js";
import { PROXENIO_URL, RATE_LIMIT_PER_HOUR, RATE_LIMIT_WRITE_PER_HOUR } from "../constants.js";

/**
 * Register all Proxenio tools on the MCP server.
 */
export function registerTools(server: McpServer): void {
  // ─── Tool 1: Platform Discovery ───
  server.registerTool(
    "proxenio_discover",
    {
      title: "Discover Proxenio Platform",
      description: `Get information about the Proxenio platform and its agent API.

Proxenio is a verified intent network for professional deal-making. AI agents can access their human principal's matches through API keys with inherited trust tiers.

This tool requires no authentication. Use it to understand the platform before connecting.

Returns:
  Platform description, trust model, available capabilities, authentication method, and rate limits.

Examples:
  - Use when: "What is Proxenio?" or "How do I connect to Proxenio?"
  - Use when: Agent needs to understand what Proxenio offers before authenticating
  - Don't use when: You already know about Proxenio and just need to read matches`,
      inputSchema: {},
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async () => {
      const info = [
        "# Proxenio — Verified Intent Network",
        "",
        "## What It Is",
        "Proxenio matches verified professionals based on declared intent and confirmed outcomes.",
        "Trust is earned through behavioral proof, not claimed through profiles.",
        "",
        "## Agent Access",
        `- **Base URL**: ${PROXENIO_URL}/api/agent`,
        "- **Auth**: API key via `X-Proxenio-Key` header (prefix: `prx_`, 36 chars)",
        "- **Key provisioning**: Human principal generates keys at /agents after email verification",
        "- **Max keys**: 3 per user",
        `- **Rate limit (read)**: ${RATE_LIMIT_PER_HOUR} requests/hour per key`,
        `- **Rate limit (write)**: ${RATE_LIMIT_WRITE_PER_HOUR} requests/hour per key`,
        "",
        "## Trust Model",
        "- Agents inherit their human principal's trust tier at request time",
        "- Trust tiers: 0 (Unverified) → 1 (Starter) → 2 (Active) → 3 (Trusted) → 4 (Proven)",
        "- Agents cannot build independent trust or exceed their principal's tier",
        "- Counterparties always see a transparency badge when interacting with an agent's principal",
        "",
        "## Available Tools",
        "1. `proxenio_set_api_key` — Configure your API key (required before other operations)",
        "2. `proxenio_get_matches` — Read principal's verified professional matches",
        "3. `proxenio_accept_match` — Accept an introduction request on behalf of principal",
        "4. `proxenio_get_deals` — Read principal's deals with counterparty context and outcomes",
        "5. `proxenio_request_intro` — Request an introduction (requires principal approval)",
        "6. `proxenio_log_outcome` — Log a deal outcome (requires principal approval)",
        "",
        "## Scope Limitations",
        "- **read_only** keys: Can read matches and deals",
        "- **read_write** keys: Can read matches and deals, accept introductions, request introductions, and log outcomes",
        "- Write actions (intro requests and outcome logging) are subject to principal approval and do not take immediate effect",
        "- Agents CANNOT bypass the matching engine's skip layers or tier gates",
        "",
        `**Status**: ${hasApiKey() ? "✓ API key configured" : "⚠ No API key set — use proxenio_set_api_key first"}`,
        "",
        `**Links**: [Platform](${PROXENIO_URL}) · [API Docs](${PROXENIO_URL}/agents/docs) · [OpenAPI Spec](${PROXENIO_URL}/api/agent/openapi.json)`,
      ];

      return {
        content: [{ type: "text" as const, text: info.join("\n") }],
      };
    }
  );

  // ─── Tool 2: Set API Key ───
  server.registerTool(
    "proxenio_set_api_key",
    {
      title: "Set Proxenio API Key",
      description: `Configure the API key for authenticating with Proxenio's agent API.

This must be called before using any authenticated Proxenio tools.

The API key is generated by a verified human principal at ${PROXENIO_URL}/agents. Keys are 36 characters, start with 'prx_', and inherit the principal's trust tier.

Args:
  - api_key (string): The full API key starting with 'prx_' (36 characters)

Returns:
  Confirmation that the key was set, or an error if the format is invalid.

Examples:
  - Use when: Setting up Proxenio access for the first time
  - Use when: Switching to a different principal's API key
  - Don't use when: Key is already configured and working`,
      inputSchema: SetApiKeyShape,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async (params) => {
      try {
        setApiKey(params.api_key);
        const prefix = params.api_key.substring(0, 12);
        return {
          content: [
            {
              type: "text" as const,
              text: `✓ API key configured (${prefix}…). You can now use all authenticated Proxenio tools.`,
            },
          ],
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 3: Get Matches ───
  server.registerTool(
    "proxenio_get_matches",
    {
      title: "Get Proxenio Matches",
      description: `Read the principal's verified professional matches from Proxenio.

Returns matches sorted by match score (descending). Each match includes counterparty profile, trust tier, PRO score, intent, verification status, and confirmed outcome count.

Requires: API key must be set via proxenio_set_api_key first.

The agent sees exactly what the human principal sees — same skip engine layers, same tier gates, same minimum score (40). Matches below 40 are never returned.

Args:
  - filter_type ('all' | 'premium' | 'strong' | 'regular'): Filter by match quality tier (default: 'all')
  - filter_status ('all' | 'pending' | 'accepted'): Filter by match status (default: 'all')
  - min_score (number, 40-100): Minimum match score threshold (default: 40)

Returns:
  Principal info, list of matches with full counterparty profiles, trust signals, and rate limit status.

Examples:
  - Use when: "Show me my matches" or "What professional connections are available?"
  - Use when: "Find my best matches" -> use filter_type='premium'
  - Use when: "Which introductions are pending?" -> use filter_status='pending'
  - Don't use when: API key has not been set yet (use proxenio_set_api_key first)

Error Handling:
  - Returns auth error if API key is invalid or revoked
  - Returns rate limit error if ${RATE_LIMIT_PER_HOUR} requests/hour exceeded
  - Returns empty list if principal has no matches (profile may be incomplete)`,
      inputSchema: GetMatchesShape,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async (params) => {
      try {
        const { data, rateLimit } = await getMatches();

        // Apply client-side filters
        let filtered = data.matches;

        if (params.filter_type !== "all") {
          filtered = filtered.filter((m) => m.match_type === params.filter_type);
        }
        if (params.filter_status !== "all") {
          filtered = filtered.filter((m) => m.status === params.filter_status);
        }
        if (params.min_score > 40) {
          filtered = filtered.filter((m) => m.match_score >= params.min_score);
        }

        const filteredResponse = { ...data, matches: filtered, meta: { ...data.meta, total_matches: filtered.length } };
        const markdown = formatMatchesMarkdown(filteredResponse, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
          structuredContent: filteredResponse,
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 4: Accept Match ───
  server.registerTool(
    "proxenio_accept_match",
    {
      title: "Accept Proxenio Introduction",
      description: `Accept an introduction request on behalf of the human principal.

This creates a deal between the principal and the counterparty. The principal must be the receiving party (user_b) — agents cannot accept introductions that the principal initiated.

IMPORTANT: This is an action with real consequences. It connects two professionals and creates a deal container. Only accept matches that align with the principal's stated intent.

Requires: API key must be set via proxenio_set_api_key first.

Args:
  - match_id (string, UUID): The match ID to accept. Get this from proxenio_get_matches results.

Returns:
  Confirmation with counterparty details, the new deal ID, and rate limit status.

Guard rails enforced by the API:
  - Principal must be a participant in the match
  - Principal must be the receiving party (user_b), not the requester
  - Match must have an active status
  - An introduction request must exist and be in pending/awaiting_consent state
  - Agent cannot accept the principal's own outgoing requests

Examples:
  - Use when: Principal wants to accept a specific pending introduction
  - Use when: Agent decides a match aligns with principal's intent and should be accepted
  - Don't use when: You haven't checked the match details first (use proxenio_get_matches)
  - Don't use when: The match was initiated by the principal (agent can only accept incoming)

Error Handling:
  - 400: Match not in correct state, no intro request exists
  - 403: Principal is not authorized (e.g., they are the requester, not receiver)
  - 404: Match ID not found
  - 429: Rate limit exceeded`,
      inputSchema: AcceptMatchShape,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async (params) => {
      try {
        const { data, rateLimit } = await acceptMatch(params.match_id);
        const markdown = formatAcceptMarkdown(data, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
          structuredContent: data,
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 5: Get Deals ───
  server.registerTool(
    "proxenio_get_deals",
    {
      title: "Get Proxenio Deals",
      description: `Read the principal's deals with counterparty context, status, and outcomes.

Returns deals sorted by most recently updated. Each deal includes counterparty profile, deal status, outcomes logged by both parties, and the originating match ID.

Requires: API key must be set via proxenio_set_api_key first.

Args:
  - filter_status ('all' | 'open' | 'closed'): Filter deals by status (default: 'all')

Returns:
  Principal info, list of deals with counterparty profiles, outcomes, and rate limit status.

Examples:
  - Use when: "Show me my deals" or "What deals do I have?"
  - Use when: "Show my open deals" -> use filter_status='open'
  - Don't use when: API key has not been set yet (use proxenio_set_api_key first)

Error Handling:
  - Returns auth error if API key is invalid or revoked
  - Returns rate limit error if ${RATE_LIMIT_PER_HOUR} requests/hour exceeded
  - Returns empty list if principal has no deals`,
      inputSchema: GetDealsShape,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async (params) => {
      try {
        const { data, rateLimit } = await getDeals();

        // Apply client-side filter
        let filtered = data.deals;

        if (params.filter_status !== "all") {
          filtered = filtered.filter((d) => d.status === params.filter_status);
        }

        const filteredResponse = { ...data, deals: filtered, meta: { ...data.meta, total_deals: filtered.length } };
        const markdown = formatDealsMarkdown(filteredResponse, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
          structuredContent: filteredResponse,
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 6: Request Introduction ───
  server.registerTool(
    "proxenio_request_intro",
    {
      title: "Request Proxenio Introduction",
      description: `Requests an introduction on behalf of the principal. This action requires principal approval and does not take immediate effect.

The principal will see the pending request in their dashboard and can approve or reject it. Only after approval does the introduction request reach the counterparty.

Requires: API key with read_write scope must be set via proxenio_set_api_key first.

Args:
  - match_id (string, UUID): The match ID to request an introduction for. Get this from proxenio_get_matches.
  - context (string, optional): Message to the counterparty (max 500 characters). Shown to the principal during approval.

Returns:
  Confirmation that the intro request was created with agent_pending status, awaiting principal approval.

Guard rails enforced by the API:
  - Key must have read_write scope
  - Match must exist and principal must be a participant
  - Match must be in active status
  - No existing intro request for this match
  - Maximum 10 pending intro requests per key
  - Maximum 2 rejections per match per key

Examples:
  - Use when: Agent identifies a match that aligns with principal's intent
  - Use when: Principal asks agent to reach out to a specific match
  - Don't use when: Key has read_only scope
  - Don't use when: You haven't checked the match details first (use proxenio_get_matches)

Error Handling:
  - 400: Match not in correct state, pending cap reached, context too long
  - 403: Read-only scope, not a participant, repeated rejections
  - 404: Match not found
  - 429: Rate limit exceeded`,
      inputSchema: RequestIntroShape,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async (params) => {
      try {
        const { data, rateLimit } = await requestIntro(params.match_id, params.context);
        const markdown = formatIntroRequestMarkdown(data, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
          structuredContent: data,
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );

  // ─── Tool 7: Log Outcome ───
  server.registerTool(
    "proxenio_log_outcome",
    {
      title: "Log Proxenio Deal Outcome",
      description: `Logs a deal outcome on behalf of the principal. This action requires principal approval and does not take immediate effect.

The principal will see the pending outcome in their dashboard and can approve or reject it. Only after approval does the outcome enter the bilateral confirmation flow with the counterparty. PRO score and trust tier are not affected until the counterparty confirms.

Requires: API key with read_write scope must be set via proxenio_set_api_key first.

Args:
  - deal_id (string, UUID): The deal ID to log an outcome for. Get this from proxenio_get_deals.
  - outcome_type (string, enum): Type of outcome. Must be one of: 'Intro', 'Pipeline Progress', 'Agreement or Deal', 'Results or Impact', 'Negative or Closing', 'Neutral or Respectful Close'.
  - outcome_description (string, optional): Description of the outcome (max 1000 characters). Shown to the principal during approval.

Returns:
  Confirmation that the outcome was logged with agent_pending status, awaiting principal approval.

Guard rails enforced by the API:
  - Key must have read_write scope
  - Deal must exist and principal must be a participant
  - Deal must be in open status
  - No existing agent_pending outcome on this deal by principal
  - Maximum 10 pending outcomes per key
  - Maximum 2 rejections per deal per key

Examples:
  - Use when: Agent knows a deal has progressed and wants to log the outcome
  - Use when: Principal asks agent to record a deal result
  - Don't use when: Key has read_only scope
  - Don't use when: You haven't checked the deal details first (use proxenio_get_deals)

Error Handling:
  - 400: Deal not in correct state, invalid outcome_type, pending cap reached, description too long
  - 403: Read-only scope, not a participant, repeated rejections
  - 404: Deal not found
  - 429: Rate limit exceeded`,
      inputSchema: LogOutcomeShape,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async (params) => {
      try {
        const { data, rateLimit } = await logOutcome(
          params.deal_id,
          params.outcome_type,
          params.outcome_description
        );
        const markdown = formatOutcomeMarkdown(data, rateLimit);

        return {
          content: [{ type: "text" as const, text: markdown }],
          structuredContent: data,
        };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );
}
